# database:
#   build: ./database
#   ports:
#     - "5432:5432"

dbpostgres:
  # image: postgres
  build: ./database
  volumes:
    - ~/sharedvolumes/postgresql:/var/lib/postgresql
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: pguser
    POSTGRES_PASSWORD: pguser
    POSTGRES_DB: utilization

rabbit:
  image: rabbitmq:3-management
  ports:
    - "4369:4369"
    - "5672:5672"
    - "15672:15672"
    - "25672:25672"

publisher:
  build: ./publisher
  environment:
    METACIRCULARITY: 1
    INTERVAL: 10
  command: python client_app.py
  entrypoint: ["./docker-entrypoint.sh"]
  links:
    - rabbit:rabbit
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

consumer:
  build: ./consumer
  command: python consumer_app.py
  entrypoint: ["./docker-entrypoint.sh"]
  links:
    - rabbit:rabbit
    - dbpostgres:dbpostgres

api:
  build: ./api
  command: python main.py
  entrypoint: ["./docker-entrypoint.sh"]
  ports:
    - "5000:5000"
  links:
    - rabbit:rabbit
    - dbpostgres:dbpostgres
